title: Genvortex
description: Sciences, climat, physique

url: "https://genvortex.github.io"
baseurl: ""

theme: jekyll-theme-chirpy
math: mathjax

markdown: kramdown
kramdown:
  math_engine: mathjax
  input: GFM

defaults:
  - scope:
      path: ""
    values:
      layout: page
