title: Genvortex
description: Sciences & Climat

url: "https://genvortex.github.io"
baseurl: ""

markdown: kramdown
kramdown:
  input: GFM
  math_engine: mathjax  # ← active le parsing LaTeX

defaults:
  - scope:
      path: ""
    values:
      layout: page  # ← utilise notre nouveau layout
